spring.application.name=harmocrew-api
server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/harmocrew}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:harmocrew}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:harmocrew}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
